@startuml customer_uc

left to right direction

actor "Khách Hàng" as KH
actor "Khách Hàng Vãng Lai" as KHVL

KH --> (Đăng nhập)
KHVL --> (Đăng ký)
KH --> (Quản lý tài khoản)
(Quản lý tài khoản) <.. (Thay đổi mật khẩu) : <<extends>>
(Quản lý tài khoản) <.. (Xem thông tin cá nhân) : <<extends>>
(Xem thông tin cá nhân) <.. (Chỉnh sửa thông itn cá nhân) : <<extends>>

KH --> (Quản lý sổ địa chỉ)
(Quản lý sổ địa chỉ) <.. (Xem thông tin địa chỉ)
(Quản lý sổ địa chỉ) <.. (Thêm địa chỉ mới) : <<extends>>
(Xem thông tin địa chỉ)<.. (Xóa địa chỉ) : <<extends>>
(Xem thông tin địa chỉ) <.. (Chỉnh sửa địa chỉ) : <<extends>>

KH --> (Quản lý đơn hàng)
(Quản lý đơn hàng) <.. (Xem đơn hàng) : <<extends>>
(Quản lý đơn hàng) <.. (Hủy đơn hàng) : <<extends>>

KH --> (Quản lý mã giảm giá cá nhân)
(Quản lý mã giảm giá cá nhân) <.. (Xem mã giám giá) : <<extends>>

KH --> (Đặt hàng)
KH --> (Thanh toán)
(Đặt hàng) ..> (Xem thông tin sách) : <<includes>>
(Đặt hàng) <.. (Thêm mã giảm giá) : <<extends>>
(Đặt hàng) <.. (Thanh toán) : <<includes>>
(Xem thông tin sách) <.. (Thêm sách vào giỏ hàng) : <<extends>>
(Xem thông tin sách) <.. (Xóa sách khỏi giỏ hàng) : <<extends>>

KH --> (Quản lý giỏ hàng)
(Quản lý giỏ hàng) <.. (Xóa sách khỏi giỏ hàng) : <<extends>>
(Quản lý giỏ hàng) <.. (Thay đổi số lượng) : <<extends>>

@enduml