CREATE TABLE books
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    create_ts    TIMESTAMP WITHOUT TIME ZONE,
    update_ts    TIMESTAMP WITHOUT TIME ZONE,
    isbn         VARCHAR(255),
    title        VARCHAR(255),
    description  VARCHAR(255),
    author       VARCHAR(255),
    price        DECIMAL,
    in_stock     INTEGER,
    url_slug     VARCHAR(255),
    publisher    VARCHAR(255),
    publish_year INTEGER,
    page_count   INTEGER,
    image_url    VARCHAR(255),
    CONSTRAINT pk_books PRIMARY KEY (id)
);

CREATE TABLE cart_items
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    create_ts TIMESTAMP WITHOUT TIME ZONE,
    update_ts TIMESTAMP WITHOUT TIME ZONE,
    quantity  INTEGER,
    cart_id   INTEGER,
    book_id   INTEGER,
    CONSTRAINT pk_cart_items PRIMARY KEY (id)
);

CREATE TABLE carts
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    create_ts   TIMESTAMP WITHOUT TIME ZONE,
    update_ts   TIMESTAMP WITHOUT TIME ZONE,
    user_id     INTEGER,
    cart_status VARCHAR(255),
    CONSTRAINT pk_carts PRIMARY KEY (id)
);

CREATE TABLE customer_addresses
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    create_ts TIMESTAMP WITHOUT TIME ZONE,
    update_ts TIMESTAMP WITHOUT TIME ZONE,
    city      VARCHAR(255),
    commune   VARCHAR(255),
    street    VARCHAR(255),
    user_id   INTEGER,
    CONSTRAINT pk_customer_addresses PRIMARY KEY (id)
);

CREATE TABLE order_items
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    create_ts         TIMESTAMP WITHOUT TIME ZONE,
    update_ts         TIMESTAMP WITHOUT TIME ZONE,
    quantity          INTEGER,
    price_at_purchase DECIMAL,
    title_at_purchase VARCHAR(255),
    isbn              VARCHAR(255),
    product_code      VARCHAR(255),
    order_id          INTEGER,
    book_id           INTEGER,
    CONSTRAINT pk_order_items PRIMARY KEY (id)
);

CREATE TABLE orders
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    create_ts   TIMESTAMP WITHOUT TIME ZONE,
    update_ts   TIMESTAMP WITHOUT TIME ZONE,
    customer_id INTEGER,
    city        VARCHAR(255),
    commune     VARCHAR(255),
    street      VARCHAR(255),
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE refresh_tokens
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    create_ts     TIMESTAMP WITHOUT TIME ZONE,
    update_ts     TIMESTAMP WITHOUT TIME ZONE,
    refresh_token VARCHAR(255),
    expiration    TIMESTAMP WITHOUT TIME ZONE,
    user_id       INTEGER,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id)
);

CREATE TABLE users
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    create_ts    TIMESTAMP WITHOUT TIME ZONE,
    update_ts    TIMESTAMP WITHOUT TIME ZONE,
    user_type    VARCHAR(255),
    email        VARCHAR(255),
    first_name   VARCHAR(255),
    last_name    VARCHAR(255),
    password     VARCHAR(255),
    phone_number VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE books
    ADD CONSTRAINT uc_books_isbn UNIQUE (isbn);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT uc_refresh_tokens_user UNIQUE (user_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE carts
    ADD CONSTRAINT FK_CARTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE cart_items
    ADD CONSTRAINT FK_CART_ITEMS_ON_BOOK FOREIGN KEY (book_id) REFERENCES books (id);

ALTER TABLE cart_items
    ADD CONSTRAINT FK_CART_ITEMS_ON_CART FOREIGN KEY (cart_id) REFERENCES carts (id);

ALTER TABLE customer_addresses
    ADD CONSTRAINT FK_CUSTOMER_ADDRESSES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES users (id);

ALTER TABLE order_items
    ADD CONSTRAINT FK_ORDER_ITEMS_ON_BOOK FOREIGN KEY (book_id) REFERENCES books (id);

ALTER TABLE order_items
    ADD CONSTRAINT FK_ORDER_ITEMS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT FK_REFRESH_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);