CREATE TABLE coupons
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    create_ts        TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    update_ts        TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    code             VARCHAR(255)                             NOT NULL,
    discount_type    VARCHAR(255),
    discount_value   DECIMAL,
    min_order_amount DECIMAL,
    max_uses         INTEGER,
    used_count       INTEGER,
    valid_from       TIMESTAMP WITHOUT TIME ZONE,
    valid_until      TIMESTAMP WITHOUT TIME ZONE,
    is_active        BOOLEAN,
    CONSTRAINT pk_coupons PRIMARY KEY (id)
);

ALTER TABLE coupons
    ADD CONSTRAINT uc_coupons_code UNIQUE (code);