CREATE TABLE collections
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    create_ts       TIMESTAMP WITHOUT TIME ZONE,
    update_ts       TIMESTAMP WITHOUT TIME ZONE,
    collection_name VARCHAR(255),
    collection_slug VARCHAR(255),
    CONSTRAINT pk_collections PRIMARY KEY (id)
);