server.port=8080
app.cors-allowed-origins=http://localhost:5173,http://localhost:5174,http://localhost:4173
app.frontend-url=http://localhost:5173

# DB
spring.datasource.url=jdbc:postgresql://localhost:54320/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

# RSA
spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:certs/public.pem
spring.security.oauth2.resourceserver.jwt.private-key-location=classpath:certs/private.pem

# JWT
app.jwt-token-expiration-seconds=900
app.jwt-refresh-expiration-seconds=86400