# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:54320/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate
spring.jpa.database-platform=
spring.jpa.show-sql=false
# drop on create to test
#spring.jpa.hibernate.ddl-auto=create-drop