spring.application.name=bookstore

spring.profiles.active=${SPRING_PROFILES_ACTIVE}
logging.level.org.springframework.security=DEBUG

payment.vnPay.url=${PAY_URL}
payment.vnPay.tmnCode=${TMN_CODE}
payment.vnPay.secretKey=${SECRET_KEY}
payment.vnPay.returnUrl=${RETURN_URL}
payment.vnPay.version=${VERSION}
payment.vnPay.command=${COMMAND}
payment.vnPay.orderType=${ORDER_TYPE}