server.port=${SERVER_PORT:8080}
spring.datasource.url=${POSTGRES_DATASOURCE_URL}
spring.datasource.username=${POSTGRES_USERNAME:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}

# Encoder - Decoder
spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:certs/public.pem
spring.security.oauth2.resourceserver.jwt.private-key-location=classpath:certs/private.pem
