@startuml uc_admin

left to right direction

"Admin" as AD

AD --> (Quản lý khách hàng)
(Quản lý khách hàng) ..> (Xem danh sách khách hàng) : <<includes>>

AD --> (Quản lý sách)
(Quản lý sách) ..> (Thêm mới sách) : <<includes>>
(Quản lý sách) ..> (Xóa sách) : <<includes>>
(Quản lý sách) ..> (Chỉnh sửa thông tin sách) : <<includes>>

AD --> (Quản lý mã giảm giá)
(Quản lý mã giảm giá) ..> (Thêm mới mã giảm giá) : <<includes>>
(Quản lý mã giảm giá) ..> (Xóa mã giảm giá) : <<includes>>
(Quản lý mã giảm giá) ..> (Chỉnh sửa mã giảm giá) : <<includes>>

AD --> (Quản lý danh mục sách)
(Quản lý danh mục sách) ..> (Thêm mới danh mục sách) : <<includes>>
(Quản lý danh mục sách) ..> (Xóa danh mục sách) : <<includes>>
(Quản lý danh mục sách) ..> (Chỉnh sửa danh mục sách) : <<includes>>

AD --> (Quản lý bộ sưu tập)
(Quản lý bộ sưu tập) ..> (Thêm mới bộ sưu tập) : <<includes>>
(Quản lý bộ sưu tập) ..> (Xóa bộ sưu tập) : <<includes>>
(Quản lý bộ sưu tập) ..> (Chỉnh sửa bộ sưu tập) : <<includes>>

AD --> (Quản lý đơn hàng)
(Quản lý đơn hàng) ..> (Cập nhật trạng thái đơn) : <<includes>>
(Quản lý đơn hàng) ..> (Xem danh sách đơn hàng) : <<includes>>

AD --> (Xem biểu đồ thống kê)

@enduml