@startuml
skinparam componentStyle rectangle
skinparam nodesep 10
skinparam ranksep 10
skinparam linetype ortho

package "Backend (Spring Boot)" {
  package Middlewares {
    [ProxyController]
    [ErrorHandlerMiddleware]
    [FileUploadMiddleware]
    [SpringSecurityFilterChain]
  }

  package Controllers {
    [AdminController]
    [AuthenticationController]
    [BookController]
    [CartController]
    [CategoryController]
    [CollectionController]
    [CouponController]
    [CustomerController]
    [OrderController]
    [PaymentController]
  }

  

  
  package Services {
    [AdminService]
    [ApplicationUserService]
    [AuthService]
    [BookService]
    [CartService]
    [CategoryService]
    [CloudinaryService]
    [CollectionService]
    [CouponService]
    [EmailService]
    [OrderService]
    [ProvinceCommuneDataService]
    [TokenService]
    [VnPayService]
  }
  package Models {
    [BaseEntity]
    [ApplicationUser]
    [Book]
    [Cart]
    [CartItem]
    [Category]
    [Collection]
    [Coupon]
    [CustomerAddressInfo]
    [Order]
    [OrderItem]
    [RefreshToken]
  }


  Middlewares .down.> Controllers
  Controllers .right.> Services
  Services .down.> Models
}
@enduml