@startuml
skinparam linetype ortho

package "Frontend (Vue + Vite)" {
  package View {
    [Routes]
    [Components]
    [Screens]
  }

  package Store {
    [auth-store]
    [admin-auth-store]
    [book-store]
    [cart-store]
    [user-profile-store]
  }

  package API {
    [AuthAPI]
    [BookAPI]
    [CartAPI]
    [AdminAPI]
    [CategoryAPI]
    [CollectionAPI]
    [CouponAPI]
    [CustomerAPI]
  }

  View .right.> API 
  View .down.> Store
  Store ..> API 
}
@enduml